apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-of-life
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-of-life
  template:
    metadata:
      labels:
        app: game-of-life
    spec:
      containers:
        - name: game-of-life
          image: docker.io/keanuwatts/theclusterflux:GameOfLife
          imagePullPolicy: Always
      imagePullSecrets:
        - name: dockerhub-secret
---
apiVersion: v1
kind: Service
metadata:
  name: game-of-life
spec:
  selector:
    app: game-of-life
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: game-of-life
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # WebSocket support annotations
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/server-snippets: |
      location / {
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
      }
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - game-of-life.theclusterflux.com
    secretName: theclusterflux
  rules:
  - host: game-of-life.theclusterflux.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: game-of-life
            port:
              number: 80
